---
- name: Clone github.com/shaunrd0/klips
  git:
    repo: https://github.com/shaunrd0/klips.git
    clone: yes
    dest: /etc/klips/ 

- name: Run Vim setup script
  script: /etc/ansible/roles/core/files/setup-vim.sh

