---
- name: Copy jail.local configuration
  template: src=files/fail2ban/jail.local dest=/etc/fail2ban/jail.local

- name: Copy jail filters
  copy: src=files/fail2ban/filter.d/ dest=/etc/fail2ban/filter.d/

