---
- name: Copy nginx configuration file
  template: src=files/nginx/nginx.conf dest=/etc/nginx/nginx.conf

- name: Copy index.html file
  template: src=files/nginx/index.html dest=/var/www/html
  notify:
    - restart nginx

